-- 분류, 가격, 이름을 조회
SELECT p.CATEGORY, MAX(p.PRICE) MAX_PRICE, 
(SELECT PRODUCT_NAME FROM FOOD_PRODUCT WHERE CATEGORY=p.CATEGORY ORDER BY PRICE DESC LIMIT 1) PRODUCT_NAME
FROM FOOD_PRODUCT p
-- 식품분류가 '과자', '국', '김치', '식용유'
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
-- 식품 가격을 기준으로 내림차순 정렬
ORDER BY 2 DESC;