-- 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트
SELECT CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK b JOIN BOOK_SALES s
ON b.BOOK_ID = s.BOOK_ID
-- 2022년 1월의 카테고리 별 도서 판매량을 합산
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY CATEGORY
-- 카테고리명을 기준으로 오름차순 정렬
ORDER BY CATEGORY;
